server:
  port: 8080


ehome:
  # 公网ip
  pu-ip: 192.168.1.242
  # 内网ip
  in-ip: 192.168.1.242
  # ehome5.0秘钥
  secret-key: hik12345
  # cms服务端口
  cms-port: 7660
  # 流媒体预览端口
  sms-preview-port: 7662
  # 流媒体回看IP
  sms-back-server-ip: 192.168.1.242
  # 流媒体回看端口
  sms-back-server-port: 9128
  # rtmp推流地址
  rtmp-url: rtmp://localhost:1935/live/
  # hls播放地址
  hls-url: https://localhost/live/index.m3u8